# Используем официальный образ MySQL как базовый образ
FROM mysql

# Определяем переменные окружения для настройки MySQL
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=my_database
ENV MYSQL_USER=my_user
ENV MYSQL_PASSWORD=my_password

# Определяем порт, который будет открыт в контейнере
EXPOSE 3306
